name: build-apk-localsend
 
on:
  workflow_dispatch:
  workflow_call:
 
env:
  JDK_VERSION: '21'
  JDK_DISTRIBUTION: 'temurin'
  ANDROID_COMPILE_SDK: '36'
  ANDROID_BUILD_TOOLS: '36.0.0'
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  FLUTTER_VERSION: '3.38.10'
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Clean runner environment
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          rm -rf ~/.android/build-cache/
          rm -rf .gradle
 
      - name: Checkout source repo
        uses: actions/checkout@main
        with:
          repository: localsend/localsend
          ref: main
          path: localsend_source
          fetch-depth: 0
          submodules: recursive
 
      - name: Checkout ci source repo
        uses: actions/checkout@main
        with:
          path: ci_source
 
      - name: Generate timestamp
        run: |
          echo "BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
 
      - name: Setup java
        uses: actions/setup-java@main
        with:
          java-version: '${{ env.JDK_VERSION }}'
          distribution: '${{ env.JDK_DISTRIBUTION }}'

      - name: Decode and write keys
        working-directory: ./localsend_source/app
        run: |
          mkdir -p android
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.p12
          cat > android/key.properties << 'EOF'
          storeFile=${{ github.workspace }}/localsend_source/app/android/app/keystore.p12
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_ALIAS_PASSWORD }}
          EOF
 
      - name: Setup flutter
        uses: subosito/flutter-action@main
        id: flutter-action
        with:
          flutter-version: '${{ env.FLUTTER_VERSION }}'
          cache: true
 
      - name: Flutter build release apk
        working-directory: ./localsend_source/app
        run: |
          flutter build apk --release --target-platform=android-arm64 --split-per-abi
 
      - name: List generated apk files
        working-directory: ./localsend_source/app
        run: |
          echo "Listing all apk files generated:"
          find ./build/app/outputs -type f -name "*.apk" | sort
 
      - name: Rename and move
        working-directory: ./localsend_source/app
        run: |
          mkdir -p "${{ github.workspace }}/dist"
          mv "./build/app/outputs/flutter-apk/app-arm64-v8a-release.apk" "${{ github.workspace }}/dist/localsend-${{ env.BUILD_DATE }}.apk"
 
      - name: Erase keystore, encrypt package and create release
        uses: ./ci_source/.github/actions/erase_aes256pac_release/
        with:
          P12_KEYSTORE_PATH: "./localsend_source/app/android/app/keystore.p12 ./localsend_source/app/android/key.properties"
          ZIP_AES256_PWD: ${{ secrets.ZIP_AES256_PWD }}
          BUILD_ARTIFACT_PATH: "./dist/localsend-${{ env.BUILD_DATE }}.apk"
          RELEASE_TAG_NAME: "${{ env.BUILD_DATE }}-localsend"